name: Cursor Agent Container Action
description: Run Cursor Agent in a container to execute AI-powered coding tasks
author: unique-dominik

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: purple

# Define your inputs here.
inputs:
  prompt:
    description: The prompt to send to Cursor Agent (use this OR prompt-file)
    required: false
  prompt-file:
    description: Path to a prompt template file. Supports envsubst variable substitution.
    required: false
  envsubst-vars:
    description: Space-separated list of env vars to substitute (e.g., '${VAR1} ${VAR2}')
    required: false
  cursor-api-key:
    description: Cursor API key for authentication (recommended to use secrets)
    required: true
  cursor-agent-version:
    description: Cursor Agent version to use (e.g., 2025.12.17-996666f)
    required: false
    default: "2025.12.17-996666f"
  model:
    description: Model to use (e.g., sonnet-4.5, claude-3-opus)
    required: false
  force:
    description: Run with --force flag
    required: false
    default: "false"
  output-format:
    description: Output format (text, json)
    required: false
  print:
    description: Print output to stdout (--print flag)
    required: false
    default: "false"

# Define your outputs here.
outputs:
  result:
    description: The result from Cursor Agent execution

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_PROMPT: ${{ inputs.prompt }}
    INPUT_PROMPT_FILE: ${{ inputs.prompt-file }}
    INPUT_ENVSUBST_VARS: ${{ inputs.envsubst-vars }}
    CURSOR_API_KEY: ${{ inputs.cursor-api-key }}
    INPUT_CURSOR_AGENT_VERSION: ${{ inputs.cursor-agent-version }}
    INPUT_MODEL: ${{ inputs.model }}
    INPUT_FORCE: ${{ inputs.force }}
    INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
    INPUT_PRINT: ${{ inputs.print }}
