name: Cursor Agent Container Action
description: Run Cursor Agent in a container to execute AI-powered coding tasks
author: unique-dominik

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: purple

# Define your inputs here.
inputs:
  prompt:
    description: The prompt to send to Cursor Agent
    required: true
  cursor-api-key:
    description: Cursor API key for authentication (recommended to use secrets)
    required: true
  cursor-agent-version:
    description: Cursor Agent version to use (e.g., 2025.12.17-996666f)
    required: false
    default: "2025.12.17-996666f"

# Define your outputs here.
outputs:
  result:
    description: The result from Cursor Agent execution

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_PROMPT: ${{ inputs.prompt }}
    CURSOR_API_KEY: ${{ inputs.cursor-api-key }}
    INPUT_CURSOR_AGENT_VERSION: ${{ inputs.cursor-agent-version }}
